# Copyright (c) Facebook, Inc. and its affiliates.
# SPDX-License-Identifier: Apache-2.0

[workspace]

members = [
    "common",
    "crypto",
    "protocol",
    "protocol-rpc"
]

[profile.release]
debug = false

[profile.bench]
debug = true
